---
galaxy_info:
  author: Mahmoud Youssif
  description: Ansible role for cloning and customising Windows VMs on VMware vCenter
  company: ""

  license: Apache-2.0

  min_ansible_version: "2.14"

  platforms:
    - name: Windows
      versions:
        - all

  galaxy_tags: []

dependencies: []
